2019-08-19 23:53:48,453 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-19 23:57:11,991 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-19 23:59:55,576 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 00:00:02,645 ERROR: Exception on /uploads/check-files-folders [POST] [in c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\routes\upload_routes.py", line 331, in check_files_folders
    subprocess.call([r'CC:\Users\arcgis\Documents\GitHub\wdc-integration\app\scripts\batch\check_files_folders.bat'])
  File "c:\arcgis\pro\bin\python\envs\flask\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\arcgis\pro\bin\python\envs\flask\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
2019-08-20 00:00:17,253 ERROR: Exception on /uploads/check-files-folders [POST] [in c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\routes\upload_routes.py", line 331, in check_files_folders
    subprocess.call([r'CC:\Users\arcgis\Documents\GitHub\wdc-integration\app\scripts\batch\check_files_folders.bat'])
  File "c:\arcgis\pro\bin\python\envs\flask\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\arcgis\pro\bin\python\envs\flask\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
2019-08-20 00:07:15,161 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 00:10:03,088 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 00:21:11,471 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 00:26:39,345 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 00:36:32,047 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 00:39:09,401 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 00:41:56,269 ERROR: Exception on /uploads/cmb [POST] [in c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\routes\upload_routes.py", line 198, in form_upload_cmb
    app.config['UPLOAD_FOLDER'], filename
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\xampp\\htdocs\\camera\\streamMobile\\uploads\\Initial_Download_03_26_19.zip'
2019-08-20 00:44:44,157 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 00:47:10,023 INFO: Beginning unzip of file. [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\scripts\unzip.py:9]
2019-08-20 00:50:19,801 INFO: Successfully unzipped file. [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\scripts\unzip.py:16]
2019-08-20 00:57:00,892 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
2019-08-20 01:00:29,576 INFO: Beginning unzip of file. [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\scripts\unzip.py:9]
2019-08-20 01:03:25,738 INFO: Successfully unzipped file. [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\scripts\unzip.py:16]
2019-08-20 01:08:02,088 ERROR: Exception on /admin/clean-temp [POST] [in c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\routes\admin_routes.py", line 230, in clean_temp_directories
    os.remove(item_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\arcgis\\Documents\\GitHub\\wdc-integration\\static\\temp\\Initial_Download_03_26_19'
2019-08-20 01:09:37,259 INFO: Microblog startup [in C:\Users\arcgis\Documents\GitHub\wdc-integration\app\__init__.py:43]
