2019-08-18 17:10:58,238 ERROR: Exception on /api/news-rss [POST] [in C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dif_user\Documents\wdc-integration\app\routes\api_routes.py", line 108, in news_rss
    with open(text_file_path, 'w', encoding='utf-8') as text_file:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\dif_user\\Documents\\wdc-integration\\static\\temp\\_Her_Ex-Boyfriend_Killed_Her_Mother._Will_the_U.S._Offer_a_Refuge?.txt'
2019-08-18 17:11:38,700 ERROR: Exception on /api/news-rss [POST] [in C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dif_user\Documents\wdc-integration\app\routes\api_routes.py", line 108, in news_rss
    with open(text_file_path, 'w', encoding='utf-8') as text_file:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\dif_user\\Documents\\wdc-integration\\static\\temp\\_Her_Ex-Boyfriend_Killed_Her_Mother._Will_the_U.S._Offer_a_Refuge?.txt'
2019-08-18 17:15:32,164 ERROR: Exception on /api/news-rss [POST] [in C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dif_user\Documents\wdc-integration\app\routes\api_routes.py", line 108, in news_rss
    with open(text_file_path, 'w', encoding='utf-8') as text_file:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\dif_user\\Documents\\wdc-integration\\static\\temp\\_Her_Ex-Boyfriend_Killed_Her_Mother._Will_the_U.S._Offer_a_Refuge?.txt'
2019-08-18 17:15:37,617 ERROR: Exception on /api/news-rss [POST] [in C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dif_user\Documents\wdc-integration\app\routes\api_routes.py", line 108, in news_rss
    with open(text_file_path, 'w', encoding='utf-8') as text_file:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\dif_user\\Documents\\wdc-integration\\static\\temp\\_Her_Ex-Boyfriend_Killed_Her_Mother._Will_the_U.S._Offer_a_Refuge?.txt'
2019-08-18 17:15:46,936 ERROR: Exception on /api/news-rss [POST] [in C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dif_user\Documents\wdc-integration\app\routes\api_routes.py", line 108, in news_rss
    with open(text_file_path, 'w', encoding='utf-8') as text_file:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\dif_user\\Documents\\wdc-integration\\static\\temp\\_Her_Ex-Boyfriend_Killed_Her_Mother._Will_the_U.S._Offer_a_Refuge?.txt'
2019-08-18 17:16:02,535 ERROR: Exception on /api/news-rss [POST] [in C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dif_user\Documents\wdc-integration\app\routes\api_routes.py", line 108, in news_rss
    with open(text_file_path, 'w', encoding='utf-8') as text_file:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\dif_user\\Documents\\wdc-integration\\static\\temp\\_Her_Ex-Boyfriend_Killed_Her_Mother._Will_the_U.S._Offer_a_Refuge?.txt'
2019-08-18 17:16:59,012 ERROR: Exception on /api/news-rss [POST] [in C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dif_user\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dif_user\Documents\wdc-integration\app\routes\api_routes.py", line 108, in news_rss
    with open(text_file_path, 'w', encoding='utf-8') as text_file:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\dif_user\\Documents\\wdc-integration\\static\\temp\\_Her_Ex-Boyfriend_Killed_Her_Mother._Will_the_U.S._Offer_a_Refuge?.txt'
2019-08-18 17:17:52,438 INFO: Microblog startup [in C:\Users\dif_user\Documents\wdc-integration\app\__init__.py:43]
