2019-08-22 01:25:18,577 ERROR: Exception on / [GET] [in c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\routes\routes.py", line 72, in index
    return render_template('index.html', title='WDC Integration API')
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\templates\base.html", line 3, in template
    {% import 'bootstrap/wtf.html' as wtf %}
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\templates\base.html", line 3, in template
    {% import 'bootstrap/wtf.html' as wtf %}
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'bootstrap'
2019-08-22 01:25:23,241 ERROR: Exception on / [GET] [in c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\routes\routes.py", line 72, in index
    return render_template('index.html', title='WDC Integration API')
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\templates\base.html", line 3, in template
    {% import 'bootstrap/wtf.html' as wtf %}
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\arcgis\Documents\GitHub\wdc-integration\app\templates\base.html", line 3, in template
    {% import 'bootstrap/wtf.html' as wtf %}
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "c:\arcgis\pro\bin\python\envs\flask\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'bootstrap'
