2019-07-07 09:03:01,843 ERROR: Exception on /api/news-rss [POST] [in /home/dif_user/wdc-integration/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/dif_user/wdc-integration/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dif_user/wdc-integration/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dif_user/wdc-integration/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dif_user/wdc-integration/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dif_user/wdc-integration/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dif_user/wdc-integration/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dif_user/wdc-integration/app/routes/api_routes.py", line 106, in news_rss
    with open(text_file_path, 'w', encoding='utf-8') as text_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dif_user/wdc-integration/static/temp/_Romania_approves_procurement_of_5_more_F-16A/B_fighters.txt'
